### ISSUE TITLE
Can't access web UI

### ISSUE THREAD

**Issue by cloudy-brain** [elkarbackup/elkarbackup#264]
Pulling my hair out :( 

my docker compose:

services:
  mysqlDb:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "elkar"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "123456"
    ports:
      - 3306:3306
    volumes:
      - elkardb:/var/lib/mysql
  elkarbackup:
    image: elkarbackup/elkarbackup
    ports:
      - 80:80
      - 443:443
    links:
      - mysqlDb
    depends_on:
      - mysqlDb
    volumes:
        - /volume1/docker/elkar/config:/etc/elkarbackup
        - /volume1/docker/elkar/data:/var/spool/elkarbackup
    environment:
      EB_DB_PASSWORD: 123456
volumes:
  elkardb:

which gives me this output

`ash-4.3# docker-compose up
Creating network "docker_default" with the default driver
Creating docker_mysqlDb_1 ...
Creating docker_mysqlDb_1 ... done
Creating docker_elkarbackup_1 ...
Creating docker_elkarbackup_1 ... error

ERROR: for docker_elkarbackup_1  Cannot start service elkarbackup: driver failed programming external connectivity on endpoint docker_elkarbackup_1 (02495e0dbff9ae6c98853e55c108686c3bbf5627e774e8e): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use

ERROR: for elkarbackup  Cannot start service elkarbackup: driver failed programming external connectivity on endpoint docker_elkarbackup_1 (02495e0dbff9ae6c98853e55c108686c3bbf5627e774e8e): Error starting userland proxy: listen tcp 0.0.0.0:443: bind: address already in use
ERROR: Encountered errors while bringing up the project.`

I've tried changing the ports externally facing in docker-compose to 8080:80 and 8181:443, but when i punch in ippadd:8181 in my browser nothing shows. 

Any ideas?

**Comment by xezpeleta** [comment]
Hi,

We've updated the docker image. Can you test again?

Here you have an exampe. Thanks:

```yaml
version: '2'

services:

  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme
    volumes:
      - /srv/mysql:/var/lib/mysql

  elkarbackup:
    image: elkarbackup/elkarbackup:1.2.7
    ports:
      - 80:80
      - 443:443
    links:
      - db
    depends_on:
      - db
    volumes:
      - /srv/elkarbackup/spool:/var/spool/elkarbackup
    environment:
      EB_DB_HOST: db
      EB_DB_PASSWORD: changeme
```
