### ISSUE TITLE
No send Mails . Docker Deploy

### ISSUE THREAD

**Issue by Nitrosito** [elkarbackup/elkarbackup#358]
Hello

I have deployed Elkarbackup in Docker SWARM using docker compose (below), I have configured the variables for sending mail but still do not send.
```
version: '3'
networks:
  traefik:
    external: true
  elkarbackup:
services:
  elkarbackup:
    image: elkarbackup/elkarbackup:1.3.1-1-apache
    environment:
      SYMFONY__DATABASE__PASSWORD: "xxxx"
      EB_CRON: "enabled"
      SYMFONY__EB__PUBLIC__KEY: "/app/.ssh/id_rsa.pub"
      SYMFONY__MAILER__TRANSPORT: "SMTP"
      SYMFONY__MAILER__HOST: "192.168.xx.xx"
      SYMFONY__MAILER__USER: "elkarbackup@xxx.xx"
      SYMFONY__MAILER__PASSWORD: "xxx**"
      SYMFONY__MAILER__FROM: "elkarbackup@xxx.xx"
    volumes:
      - ./backups:/app/backups
      - ./uploads:/app/uploads
      - ./sshkeys:/app/.ssh
    deploy:
      labels:
        traefik.port: 80
        traefik.backend.loadbalancer.sticky: "true"
        traefik.frontend.rule: "Host:elkarbackup.xxx.xx"
        traefik.docker.network: "traefik"
        traefik.frontend.redirect.entryPoint: "https"
    networks:
      - traefik
      - elkarbackup
  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "xxx"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - elkarbackup

```
 I not see the options to configure mail from the GUI

a greeting
