### ISSUE TITLE
PID exists and so does process, cannot continue

### ISSUE THREAD

**Issue by onfire4g05** [elkarbackup/elkarbackup#508]
I just recently moved my Docker instance from an x86 server to an arm64, and in doing so updated to version 2. Everything seems to be fine. This all could be helpful, because I may have some issue somewhere in my configuration. I'm also using wireguard to connect Elkarbackup to my off-site servers, if that matters at all. Permissions seem correct and files do seem to be transferring correctly.

Anyway, I'm getting the following result and wondering if anyone might know how to fix it?

```
[2021-04-26T22:06:05] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.1_1.cfg sync: started
[2021-04-26T22:06:05] Setting locale to POSIX "C"
[2021-04-26T22:06:05] echo 48868 > /app/tmp/rsnapshot.0001_0001.pid
[2021-04-26T22:06:05] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.1_1.cfg sync: started
[2021-04-26T22:06:05] Setting locale to POSIX "C"
[2021-04-26T22:06:05] /usr/bin/rsnapshot -c /app/tmp/rsnapshot.1_1.cfg sync: ERROR: Lockfile /app/tmp/rsnapshot.0001_0001.pid exists and so does its process, can not continue

```

**Comment by xezpeleta** [comment]
https://github.com/elkarbackup/elkarbackup/wiki/FAQ#backup-job-fails-lockfile-tmpsomethingpid-exists-and-so-does-its-process-can-not-continue

**Comment by onfire4g05** [comment]
Hmm, neither are true. I'm kicking these off manually.

**Comment by xezpeleta** [comment]
Then you probably stopped your Docker container while *rsnapshot* was running.

**Comment by onfire4g05** [comment]
It seems to happen all the time, and on random jobs (doesn't seem consistently on a single one). Docker never stops. It looks like it's running the command (from the log) multiple times, or is it not?

I'm not doing anything weird, and I only have one instance running and only one docker instance running.

**Comment by xezpeleta** [comment]
Can you share your Docker configuration? (docker-compose.yml or customized Elkarbackup environment variables)

What policy are you using in this example? (client 1, job 1).

**Comment by onfire4g05** [comment]
Default policy: daily @ 1am, weekly @ 2am, monthly @ 3am

```
services:
  elkarbackup:
    image: elkarbackup/elkarbackup:2.0.0
    environment:
      TZ: "America/Chicago"
      SYMFONY__DATABASE__PASSWORD: "zzzz"
      SYMFONY__DATABASE__HOST: "172.17.0.1"
      EB_CRON: "enabled"
      SYMFONY__MAILER__TRANSPORT: "smtp"
      SYMFONY__MAILER__HOST: "zzz"
      SYMFONY__MAILER__USER: "zzzz"
      SYMFONY__MAILER__PASSWORD: "zzzz"
      SYMFONY__MAILER__FROM: "zzz@zzz"
      SYMFONY__EB__MAX__PARALLEL__JOBS: 2
    volumes:
      - './backups:/app/backups'
      - './uploads:/app/uploads'
      - './sshkeys:/app/.ssh'
      - './apps:/app/bin'
      - './tmp:/app/tmp'
    ports:
      - 80:80
    restart: unless-stopped
```
