### ISSUE TITLE
Synology: setfacl errors in docker.

### ISSUE THREAD

**Issue by tracure1337** [elkarbackup/elkarbackup#581]
### Describe the bug

A clear and concise description of what the bug is. Include the following information:

- Elkarbackup version:  elkarbackup/elkarbackup    latest              cf08b82ecea4        3 months ago        657MB
- HOST OS : Linux  3.10.105 #25556 SMP Thu Mar 18 12:57:19 CST 2021 x86_64 GNU/Linux synology_braswell_916+

### Steps to reproduce the behavior

1.  Start this docker -compose
```
version: "3"

services:
  db:
    image: mariadb:10.4
    environment:
    - MARIADB_ROOT_PASSWORD=test
    - SYMFONY__DATABASE__USER=root
    - SYMFONY__DATABASE__PASSWORD=3nxHeEf939gm*do8
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /volume1/docker/elkarbackup/db:/var/lib/mysql
  db-backup:
    image: mariadb:10.4
    environment:
    - MYSQL_PWD=test
    - MYSQL_USER=root
    - BACKUP_NUM_KEEP=7
    - BACKUP_FREQUENCY=1d
    volumes:
      - /volume1/docker/elkarbackup/database-dump:/dump
      - /etc/localtime:/etc/localtime:ro
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        mysqldump -h db --all-databases | gzip -c > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.sql.gz
        (ls -t /dump/dump*.sql.gz|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.sql.gz)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'

  app:
    image: elkarbackup/elkarbackup
    environment:
    - SYMFONY__DATABASE__PASSWORD=3nxHeEf939gm*do8
    - EB_CRON=enabled
    - TZ='Etc/UTC'
    ports:
      - 9500:80
    volumes:
       - /etc/localtime:/etc/localtime:ro
       - /volume1/docker/elkarbackup/backups:/app/backups
       - /volume1/docker/elkarbackup/uploads:/app/uploads
       - /volume1/docker/elkarbackup/sshkeys:/app/.ssh
```
3. 

### Expected vs actual behavior

I can reach the webUI.

### Logs

```
setfacl: app/cache/prod/annotations/5f: Operation not supported
setfacl: app/cache/prod/annotations/94: Operation not supported
setfacl: app/cache/prod/annotations/b4: Operation not supported
setfacl: app/cache/prod/annotations/96: Operation not supported
setfacl: app/cache/prod/annotations/d5: Operation not supported
```
for many many files.

which results in the webUI throwing:

```

Fatal error: Uncaught RuntimeException: Cache directory "/app/elkarbackup/app/cache/prod" is not writable. in /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php:280 Stack trace: #0 /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php(159): Symfony\Component\ClassLoader\ClassCollectionLoader::writeCacheFile('/app/elkarbacku...', '<?php \nnamespac...') #1 /app/elkarbackup/app/bootstrap.php.cache(2722): Symfony\Component\ClassLoader\ClassCollectionLoader::load(Array, Array, 'classes', false, false, '.php') #2 /app/elkarbackup/app/bootstrap.php.cache(2558): Symfony\Component\HttpKernel\Kernel->doLoadClassCache('classes', '.php') #3 /app/elkarbackup/app/bootstrap.php.cache(2592): Symfony\Component\HttpKernel\Kernel->boot() #4 /app/elkarbackup/web/app.php(32): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #5 {main} thrown in /app/elkarbackup/vendor/symfony/symfony/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php on line 280

```

I executed setfacl  inside the container and have no problem. setfacl does not exist on the hostOS but that shouldn't matter no?

the user creating the mount folders is member of the docker group and many other docker-compose/portainer stacks work without issues.

Anyone has any idea on why this isn't working?

The database was correctly initialized and works too.

Thanks in advance. This is bugging me for days :)

**Comment by cocoonkid** [comment]
I tried the following as well, same problem.

I recreated all dirs and did a proper docker volume prune as well..


```
version: '3'

services:
  elkarbackup:
    image: elkarbackup/elkarbackup:latest
    environment:
      SYMFONY__DATABASE__PASSWORD: "test"
      EB_CRON: "enabled"
    volumes:
        - /volume1/docker/elkarbackup/backups:/app/backups
        - /volume1/docker/elkarbackup/uploads:/app/uploads
        - /volume1/docker/elkarbackup/sshkeys:/app/.ssh
    ports:
      - 8500:80

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "test"
    volumes:
      - /volume1/docker/elkarbackup/db:/var/lib/mysql
     
```
