### ISSUE TITLE
Exception occurred while flushing email queue

### ISSUE THREAD

**Issue by leviscop** [elkarbackup/elkarbackup#612]
### Describe the bug

Does't send emails after job to set mail address over my external mail server (https://github.com/mailcow/mailcow-dockerized)

- Elkarbackup version: v2.1.0
- OS: Ubuntu 20.04 Focal
- Docker image name: elkarbackup/elkarbackup:latest

### Steps to reproduce the behavior

1. Deploy docker image with env variables for external mail server
2. Run a backup job configured to send all messages to mail address

### Expected vs actual behavior

Email should be send over external mail server to my mail address

### Logs

`ERROR     [app] Exception occurred while flushing email queue: Expected response code 354 but got an empty response ["user" => null,"user_email" => "","user_id" => "","user_name" => ""]`

My docker-compose file:

```
version: '3'

services:
  elkarbackup:
    image: elkarbackup/elkarbackup:latest
    restart: unless-stopped
    container_name: elkarbackup-manager
    environment:
      - SYMFONY__DATABASE__DRIVER=pdo_mysql
      - SYMFONY__DATABASE__PORT=3306
      - SYMFONY__DATABASE__HOST=database
      - SYMFONY__DATABASE__NAME=${MYSQL_DATABASE}
      - SYMFONY__DATABASE__USER=${MYSQL_USER}
      - SYMFONY__DATABASE__PASSWORD=${MYSQL_PASSWORD}
      - SYMFONY__MAILER__PORT=587
      - SYMFONY__MAILER__ENCRYPTION=TLS
      - SYMFONY__MAILER__TRANSPORT
      - SYMFONY__MAILER__HOST
      - SYMFONY__MAILER__USER
      - SYMFONY__MAILER__PASSWORD
      - SYMFONY__MAILER__FROM
      - TZ=Europe/Berlin
      - PHP_TZ=Europe/Berlin
      - EB_CRON=enabled
    labels:
      - traefik.enable=true
      - traefik.http.services.elkar.loadbalancer.server.port=80
      - traefik.http.routers.elkar.rule=Host(`elkar.storage-1.swarm.leviscop.net`)
      - traefik.http.routers.elkar.entrypoints=web
      - traefik.http.routers.elkar.middlewares=elkar-https
      - traefik.http.middlewares.elkar-https.redirectscheme.scheme=https
      - traefik.http.routers.elkar-secure.rule=Host(`elkar.storage-1.swarm.leviscop.net`)
      - traefik.http.routers.elkar-secure.entrypoints=websecure
      - traefik.http.routers.elkar-secure.service=elkar
      - traefik.http.routers.elkar-secure.tls=true
      - traefik.http.routers.elkar-secure.tls.certresolver=letsencrypt
      - traefik.docker.network=gateway
    volumes:
      - /volume/elkarbackup/storage:/app/backups
      - /volume/elkarbackup/scripts:/app/uploads
      - /volume/elkarbackup/sshkeys:/app/.ssh
      - /volume/elkarbackup/data/parameters.yaml:/app/elkarbackup/config/parameters.yaml
    networks:
      - default
      - gateway

  database:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: elkarbackup-database
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - /volume/elkarbackup/database:/var/lib/mysql
    networks:
      default:
        aliases:
          - database
      database:
        aliases:
          - elkardb

networks:
  default:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
        - subnet: fd00:172:18::/48
  gateway:
    external: true
  database:
    external: true
```

The .env file used for variables:

```
# ------------------------------
# elkarbackup configuration
# ------------------------------

# elkar mailserver connection

SYMFONY__MAILER__TRANSPORT=smtp
SYMFONY__MAILER__HOST=mx1.leviscop.email
SYMFONY__MAILER__USER=elkarbackup@leviscop.net
SYMFONY__MAILER__PASSWORD=xxxxxx
SYMFONY__MAILER__FROM=elkarbackup@leviscop.net

# database configuration

MYSQL_ROOT_PASSWORD=xxxxxx
MYSQL_DATABASE=elkarbackup
MYSQL_USER=elkarbackup
MYSQL_PASSWORD=xxxxxx
```

Edited config/parameters.yaml for mailer port and encryption:
(see issue #605 )

```
parameters:
    database_driver: '%env(SYMFONY__DATABASE__DRIVER)%'
    database_path: '%env(SYMFONY__DATABASE__PATH)%'
    database_host: '%env(SYMFONY__DATABASE__HOST)%'
    database_port: '%env(SYMFONY__DATABASE__PORT)%'
    database_name: '%env(SYMFONY__DATABASE__NAME)%'
    database_user: '%env(SYMFONY__DATABASE__USER)%'
    database_password: '%env(SYMFONY__DATABASE__PASSWORD)%'
    mailer_port: '%env(SYMFONY__MAILER__PORT)%'
    mailer_encryption: '%env(SYMFONY__MAILER__ENCRYPTION)%'
    mailer_transport: '%env(SYMFONY__MAILER__TRANSPORT)%'
    mailer_host: '%env(SYMFONY__MAILER__HOST)%'
    mailer_user: '%env(SYMFONY__MAILER__USER)%'
    mailer_password: '%env(SYMFONY__MAILER__PASSWORD)%'
    mailer_from: '%env(SYMFONY__MAILER__FROM)%'
    locale: en
    secret: '%env(SYMFONY__EB__SECRET)%'
    upload_dir: '%env(SYMFONY__EB__UPLOAD__DIR)%'
    backup_dir: '%env(SYMFONY__EB__BACKUP__DIR)%'
    public_key: '%env(SYMFONY__EB__PUBLIC__KEY)%'
    max_log_age: P1Y
    tmp_dir: '%env(SYMFONY__EB__TMP__DIR)%'
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
    url_prefix: '%env(SYMFONY__EB__URL__PREFIX)%'
    disable_background: false
    home: /app/elkarbackup
    max_parallel_jobs: '%env(SYMFONY__EB__MAX__PARALLEL__JOBS)%'
    post_on_pre_fail: '%env(SYMFONY__EB__POST__ON__PRE__FAIL)%'
```

Please let me know if you need any additional details or logs I can provide.
