### ISSUE TITLE
Debian11 / Debconf unable to set remote mysql

### ISSUE THREAD

**Issue by brammp** [elkarbackup/elkarbackup#614]
### Description
Unable to use a remote MySQL/MariaDB server when using `debconf-set-selections`  to configure it

### Environment info
- Elkarbackup version: v2.1.0
- OS: Debian 11
- Deb package version: elkarbackup 2.1.0 

### Steps to reproduce the behavior

1.  Set DB settings using  debconf-set-selections
```
debconf-set-selections <<< "elkarbackup elkarbackup/dbname string test"
debconf-set-selections <<< "elkarbackup elkarbackup/dbusername string test"
debconf-set-selections <<< "elkarbackup elkarbackup/dbuserpassword string test"
debconf-set-selections <<< "elkarbackup elkarbackup/dbhost string 192.168.2.36"
```
2. Following installation documentation except step 2 (https://docs.elkarbackup.org/docs/installation.html)

### Work around/alternative to get it working
Create the parameters (/etc/elkarbackup/parameters.yaml) file before running 'apt install elkarbackup'
Example file:
```
/etc/elkarbackup/parameters.yaml
parameters:
    database_driver: pdo_mysql
    database_host: 192.168.2.36
    database_port: null
    database_name: test
    database_user: test
    database_password: test
    mailer_transport: smtp
    mailer_host: localhost
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeItElkarbackup
    database_path: null
    upload_dir: /var/spool/elkarbackup/uploads
    public_key: /var/lib/elkarbackup/.ssh/id_rsa.pub
    max_log_age: P1Y
    tmp_dir: /tmp
    rsnapshot: /usr/bin/rsnapshot
    warning_load_level: 0.8
    pagination_lines_per_page: 20
    url_prefix: null
    disable_background: false
    mailer_from: null
    home: /var/lib/elkarbackup
    max_parallel_jobs: 1
    post_on_pre_fail: true
```

### Expected vs actual behavior

Expected: should install successfully and use the remote DB server
What actually happens: Installation fails (see log below)

### Logs (Output from apt)
```
Setting up elkarbackup (2.1.0) ...
DB seems to be ready
Adding missing parameters as required
Delete cache content
Update DB

In AbstractMySQLDriver.php line 112:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
  ectory                                                                       
                                                                               

In Exception.php line 18:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 38:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

Create root user
14:14:34 CRITICAL  [console] Error thrown while running command "elkarbackup:create_admin". Message: "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory" ["exception" => Doctrine\DBAL\Exception\ConnectionException^ { …},"command" => "elkarbackup:create_admin","message" => "An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory"] ["user" => null,"user_email" => "","user_id" => "","user_name" => ""]

In AbstractMySQLDriver.php line 112:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
  ectory                                                                       
                                                                               

In Exception.php line 18:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 38:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

elkarbackup:create_admin [--reset] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Clean cache

In FileLoader.php line 180:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
  ectory in . (which is being imported from "/usr/share/elkarbackup/config/ro  
  utes/api_platform.yaml"). Make sure there is a loader supporting the "api_p  
  latform" type.                                                               
                                                                               

In AbstractMySQLDriver.php line 112:
                                                                               
  An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or dir  
  ectory                                                                       
                                                                               

In Exception.php line 18:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

In PDOConnection.php line 38:
                                                    
  SQLSTATE[HY000] [2002] No such file or directory  
                                                    

cache:clear [--no-warmup] [--no-optional-warmers] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

Install assets

 Installing assets as hard copies.

 --- ------------------- ---------------- 
      Bundle              Method / Error  
 --- ------------------- ---------------- 
  ✔   ApiPlatformBundle   copy            
 --- ------------------- ---------------- 

 ! [NOTE] Some assets were installed via copy. If you make changes to these     
 !        assets you have to run this command again.                            

                                                                                
 [OK] All assets were successfully installed.                                   
                                                                                

Invalidate sessions
Warning: The home dir /var/lib/elkarbackup you specified already exists.
Adding system user `elkarbackup' (UID 107) ...
```
